steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-6959e293-8f41-4ed2-a5c/dograh-repo/dograh-api:latest', '-f', 'api/Dockerfile', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-6959e293-8f41-4ed2-a5c/dograh-repo/dograh-api:latest']
options:
  machineType: 'E2_HIGHCPU_8'
