steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dailsmart-496415/dograh-repo/dailsmart-api:latest', '-f', 'api/Dockerfile', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dailsmart-496415/dograh-repo/dailsmart-api:latest']
options:
  machineType: 'E2_HIGHCPU_8'
