steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dailsmart-496415/dograh-repo/dailsmart-ui:latest', '--build-arg', 'NEXT_PUBLIC_BACKEND_URL=https://dailsmart-api-96580183651.us-central1.run.app', '-f', 'ui/Dockerfile', '.']
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dailsmart-496415/dograh-repo/dailsmart-ui:latest']
options:
  machineType: 'E2_HIGHCPU_8'
