[from-external]
exten => _+X.,1,NoOp(Incoming call from trunk to AI Extension with plus: ${EXTEN})
 same => n,Set(JITTERBUFFER(adaptive)=default)
 same => n,Stasis(dograh)
 same => n,Hangup()

exten => _X.,1,NoOp(Incoming call from trunk to AI Extension: ${EXTEN})
 same => n,Set(JITTERBUFFER(adaptive)=default)
 same => n,Stasis(dograh)
 same => n,Hangup()

[default]
exten => _+X.,1,NoOp(Outbound call from Dograh via Dynamic Trunk ID: ${TRUNK_ID})
 same => n,Set(JITTERBUFFER(adaptive)=default)
 same => n,Set(CALLERID(num)=${CALLER_ID_NUM})
 same => n,Set(CALLERID(name)=${CALLER_ID_NAME})
 same => n,Set(CLEAN_NUMBER=${FILTER(0123456789+,${EXTEN})})
 same => n,NoOp(Cleaned number to dial: ${CLEAN_NUMBER} using CallerID: ${CALLERID(num)})
 same => n,Dial(PJSIP/endpoint_${TRUNK_ID}/sip:${CLEAN_NUMBER}@${SIP_DOMAIN})
 same => n,Hangup()

exten => _X.,1,NoOp(Outbound call from Dograh via Dynamic Trunk ID: ${TRUNK_ID})
 same => n,Set(JITTERBUFFER(adaptive)=default)
 same => n,Set(CALLERID(num)=${CALLER_ID_NUM})
 same => n,Set(CALLERID(name)=${CALLER_ID_NAME})
 same => n,Set(CLEAN_NUMBER=${FILTER(0123456789+,${EXTEN})})
 same => n,NoOp(Cleaned number to dial: ${CLEAN_NUMBER} using CallerID: ${CALLERID(num)})
 same => n,Dial(PJSIP/endpoint_${TRUNK_ID}/sip:${CLEAN_NUMBER}@${SIP_DOMAIN})
 same => n,Hangup()

exten => h,1,NoOp(Outbound Dial finished. Status=${DIALSTATUS} RunID=${WORKFLOW_RUN_ID})
 same => n,ExecIf($["${DIALSTATUS}" != "ANSWER" & "${WORKFLOW_RUN_ID}" != ""]?CURL(http://api:8000/api/v1/telephony/internal/dial-status?workflow_run_id=${WORKFLOW_RUN_ID}&dial_status=${DIALSTATUS},))

